set nocompatible

set clipboard=unnamed

let mapleader = ","

" enable syntax and plugins (for netrw)
syntax enable
filetype plugin on

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we tab complete
set wildmenu

set backspace=indent,eol,start


nmap <c-s> :w<CR>
imap <c-s> <Esc>:w<CR>

" Show always the status
set laststatus=2

call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go'
Plug 'itchyny/lightline.vim'
Plug 'NLKNguyen/papercolor-theme'
Plug 'Valloric/YouCompleteMe'
Plug 'junegunn/goyo.vim'
Plug 'airblade/vim-gitgutter'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'

call plug#end()

set background=dark

set number relativenumber

set termguicolors

colorscheme PaperColor

set ttimeoutlen=50

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

nnoremap <leader>jd :YcmCompleter GoTo<CR>





function! ProseMode()
  call goyo#execute(0, [])
  set spell noci nosi noai nolist noshowmode noshowcmd
  set complete+=s
  "set bg=light
  "if !has('gui_running')
    "let g:solarized_termcolors=256
  "endif
  "colors solarized
endfunction

command! ProseMode call ProseMode()
nmap <leader>p :ProseMode<CR>

