SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_TIME_SHOW=true

# Vim
SPACESHIP_VI_MODE_INSERT="\033[32;1;1m[I]\033[0m"
SPACESHIP_VI_MODE_NORMAL="\033[31;1m[N]\033[0m"

# Battery
SPACESHIP_BATTERY_THRESHOLD=25

# Dir
SPACESHIP_DIR_COLOR=cyan
SPACESHIP_DIR_PREFIX=$'%F{$SPACESHIP_DIR_COLOR}\ue5fe '

# Git
SPACESHIP_GIT_BRANCH_PREFIX=$'\ue725 '
SPACESHIP_GIT_SYMBOL=$'\ue725 '
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_STATUS_PREFIX=""
SPACESHIP_GIT_STATUS_SUFFIX=""

# Pyenv
SPACESHIP_PYENV_SYMBOL=$'\ue73c '
SPACESHIP_PYENV_PREFIX=""
PACESHIP_PYENV_SUFFIX=""

# Python
SPACESHIP_VENV_SYMBOL=$'\ue73c '
SPACESHIP_VENV_PREFIX=""
SPACESHIP_VENV_SUFFIX=""

# Golang
SPACESHIP_GOLANG_SYMBOL=$'\ufcd1 '
SPACESHIP_GOLANG_PREFIX=""
SPACESHIP_GOLANG_SUFFIX=""
