SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_TIME_SHOW=true
SPACESHIP_GIT_BRANCH_PREFIX=$'\ue725 '
#export SPACESHIP_GIT_BRANCH_PREFIX=$'\ue725 '
SPACESHIP_GIT_SYMBOL=$'\ue725 '
#export SPACESHIP_GIT_SYMBOL=$'\ue725 '
SPACESHIP_PYENV_SYMBOL=$'\ue73c '
SPACESHIP_GOLANG_SYMBOL=$'\ufcd1 '
