typeset -g BASE_ZSH_CONFIG=${0:a:h}
source $BASE_ZSH_CONFIG/antigen.zsh
PATH+=:~/go/bin
PATH+=:~/dotfiles/bin
#antigen use oh-my-zsh

zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
forgit_add=gai

case `uname` in
  Darwin)
    antigen bundle brew
  ;;
  Linux)
#    antigen bundle archlinux
  ;;
esac


antigen bundle git
antigen bundle docker
antigen bundle pip
antigen bundle command-not-found
antigen bundle golang
antigen bundle colorize
antigen bundle fzf
antigen bundle compleat
antigen bundle zsh-users/fizsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle wfxr/forgit
# antigen bundle globalias
#antigen bundle autojump
#antigen bundle common-aliases

#antigen theme bhilburn/powerlevel9k powerlevel9k
source $BASE_ZSH_CONFIG/spaceship.zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source $BASE_ZSH_CONFIG/p10k.zsh

# antigen theme https://github.com/denysdovhan/spaceship-prompt spaceship
# spaceship_vi_mode_enable
antigen theme romkatv/powerlevel10k
antigen apply

# source $BASE_ZSH_CONFIG/zsh-autosuggestions.zsh/zsh-autosuggestions.zsh
   
setopt prompt_subst
#Custom titlebar
echo -e "\033]Garcy\007"
# Customize iterm.
echo -e "\033]6;1;bg;red;brightness;28\a\033]6;1;bg;blue;brightness;28\a\033]6;1;bg;green;brightness;28\a"



HISTSIZE=10000
SAVEHIST=10000

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data
setopt AUTO_CD # Automatic cd

# Timeout for vim
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey 'jk' vi-cmd-mode
bindkey "^?" backward-delete-char
# vim-style command-line
# bindkey -M viins 'jk' vi-cmd-mode

export KEYTIMEOUT=1

# FZF
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --color=fg:-1,bg:-1,hl:#ff6d19 --color=fg+:#d0d0d0,bg+:#262626,hl+:#ff0000 --color=info:#87ff00,prompt:#87ff00,pointer:#87ff00 --color=marker:#82c737,spinner:#87ff00,header:#87afaf'
export FZF_DEFAULT_COMMAND="fd --type file --color=always --follow --hidden --no-ignore-vcs --exclude .git"
export FZF_CTRL_T_OPTS=' --preview "bat --color=always {}"'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export FZF_DEFAULT_OPTS="--ansi"

## Command history configuration
if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi

source $BASE_ZSH_CONFIG/alias.zsh
source $BASE_ZSH_CONFIG/functions.zsh
source $BASE_ZSH_CONFIG/bgnotify.zsh

banner


export EDITOR=nvim
alias ctags="`brew --prefix`/bin/ctags"
setopt HIST_IGNORE_SPACE


# Replace zle-keymap-select
# Thank to LukeSmithxyz
function zle-keymap-select {
	if [[ ${KEYMAP} == vicmd ]] ||
		[[ $1 = 'block' ]]; then
			echo -ne '\e[1 q'
	elif [[ ${KEYMAP} == main ]] ||
		[[ ${KEYMAP} == viins ]] ||
		[[ ${KEYMAP} = '' ]] ||
		[[ $1 = 'beam' ]]; then
			echo -ne '\e[5 q'
	fi
	zle reset-prompt
	zle -R
}
zle -N zle-keymap-select

# .zshrc

_fix_cursor() {
	echo -ne '\e[5 q'
}

precmd_functions+=(_fix_cursor)

# Expand alias con (C-x a)
bindkey "^Xa" _expand_alias
