
source ~/dotfiles/zsh/antigen.zsh
PATH+=:~/go/bin
#antigen use oh-my-zsh

zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

case `uname` in
  Darwin)
    antigen bundle brew
  ;;
  Linux)
#    antigen bundle archlinux
  ;;
esac

source ~/dotfiles/zsh/powerlevel9k.zsh

antigen bundle git
antigen bundle docker
antigen bundle pip
antigen bundle command-not-found
#antigen bundle autojump
#antigen bundle common-aliases
antigen bundle compleat
antigen bundle zsh-users/fizsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle golang
antigen bundle colorize
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle tarruda/zsh-autosuggestions


antigen theme bhilburn/powerlevel9k powerlevel9k
antigen apply

# source ~/dotfiles/zsh/zsh-autosuggestions.zsh/zsh-autosuggestions.zsh
   
setopt prompt_subst

echo "  ________                            ";
echo " /  _____/_____ _______   ____ ___.__.";
echo "/   \  ___\__  \\_  __ \_/ ___<   |  |";
echo "\    \_\  \/ __ \|  | \/\  \___\___  |";
echo " \______  (____  /__|    \___  > ____|";
echo "        \/     \/            \/\/     ";
echo "";
# Font Graffiti 

stty -ixon


HISTSIZE=10000
SAVEHIST=10000

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data

## Command history configuration
if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi



alias dvimrc='vim ~/dotfiles/vim/vimrc'
alias dzshrc='vim ~/dotfiles/zsh/zshrc'
alias dtmux='vim ~/dotfiles/tmux/tmux.conf'
alias ..='cd ..'
alias ...='cd ../..'

